Algoritmo "Graus"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : R a í s s a
// Data atual  :14/03/2 0 2 1
Var
// Seção de Declarações das variáveis
c,f: real

Inicio

escreval("Digite a temperatura em ºF: ")
leia(f)

c <- (5 * (f-32) / 9)

escreval("A temperatura em ºC é: ", c)

Fimalgoritmo