algoritmo "Quadrado"
// Função : Irá calcular a area do quadrado
// Autor : Raíssa Bespalec Dalóia
// Data : 02/03/2021
var
//Declaracao de variaveis
ladoQuadrado, area: real
inicio
//entrada de dados
escreva("Digite a lateral do quadrado em centímetros")
leia(ladoQuadrado)

//processamento
area <- (ladoQuadrado*ladoQuadrado)

//saida
escreva("A area do Quadrado e: ", area,"cm²")

fimalgoritmo
