algoritmo "Retângulo"
// Função : Calcular a área de um retãngulo
// Autor : Raíssa Bespalec
// Data : 02/03/2021
var
area,base,alt: real

inicio
//entrada de dados
escreva("Digite a altura do retângulo em centímetros")
leia(alt)

escreva("Digite a base do retângulo em centímetros " )
leia(base)

//processamento
area <- alt*base

//saida
escreval("A área do retângulo é: ", area , "cm²" )
  
fimalgoritmo
