algoritmo "Triangulo"
// Função : Irá calcular a area do triangulo
// Autor : Raíssa Bespalec
// Data : 02/03/2021
var
area,base,alt: real
inicio
//entrada de dados
escreva("Digite a base do triângulo em centímetros")
leia(base)

escreva("Digite a altura do triângulo em centímetros ")
leia(alt)

//processamento
area <- (base*alt)/2

//saída
escreva("A área do triângulo é: ", area,"cm²")

fimalgoritmo
